services:
    greenmail:
        image: greenmail/standalone:latest
        environment:
            - GREENMAIL_OPTS=-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose
        ports:
            - "3143:3143"
