---
name: Bug Report
about: Report a bug with ImapEngine.
---

**Environment**
- **PHP version:**
- **Operating System:**
- **ImapEngine version:**
- **IMAP server:** (e.g., Gmail, Yahoo, etc.)

**IMAP Debug Logs**
To report a bug regarding query and/or operation related issues, you **must** include 
IMAP logs obtained by enabling one of the debug options as described in the README. 
Issues without this information will be immediately closed.

To log this information, enable the `debug` option in your 
`Mailbox` configuration with one of the following values:

- Set `debug` to `true` to output logs to the console, **or**
- Set `debug` to a file path (e.g., `'/path/to/log/file.log'`) to log to a file, **or**
- Provide a fully-qualified custom logger class name that implements `DirectoryTree\ImapEngine\Connection\Loggers\LoggerInterface`.
